<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
<v t="amd.20150915153206.1" a="E"><vh>專案說明</vh>
<v t="amd.20150919102209.1" a="E"><vh>使用工具</vh>
<v t="amd.20150919112415.1"><vh>影片檔案</vh></v>
</v>
<v t="amd.20150919102541.1"><vh>pelican 與 Markdown</vh></v>
</v>
</v>
<v t="amd.20150919102739.1" a="E"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20150919103428.1"><vh>reveal.js 設定</vh></v>
<v t="amd.20150919103341.1"><vh>Jupyter 設定</vh>
<v t="amd.20150919103923.1"><vh>設定檔案位置</vh></v>
<v t="amd.20150919104249.1"><vh>檢查 profile 位置</vh></v>
</v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
<v t="amd.20150919112710.1" a="E"><vh>@path pelican</vh>
<v t="amd.20150919113340.1"><vh>以下為與 pelican 有關的設定檔案</vh></v>
<v t="amd.20150919113132.1"><vh>@edit publishconf.py</vh></v>
</v>
</v>
<v t="amd.20150919113957.1"><vh>以下為 pelican 文章</vh></v>
<v t="amd.20150919124128.1"><vh>@button pelican content</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican\content</vh>
<v t="amd.20150919114035.1"><vh>@edit 40323153_cp_w1.md</vh></v>
<v t="123.20151118141557.1"><vh>@edit 40323153_cp_w2.md</vh></v>
<v t="123.20151118224234.1"><vh>@edit 40323153_cp_w3.md</vh></v>
<v t="123.20151118224237.1"><vh>@edit 40323153_cp_w4.md</vh></v>
<v t="123.20151118224248.1"><vh>@edit 40323153_cp_w5.md</vh></v>
<v t="123.20151118224239.1"><vh>@edit 40323153_cp_w6.md</vh></v>
<v t="123.20151118224243.1"><vh>@edit 40323153_cp_w7.md</vh></v>
<v t="123.20151118224241.1"><vh>@edit 40323153_cp_w8.md</vh></v>
<v t="123.20160109140206.1"><vh>@edit 40323153_cp_w11.md</vh></v>
<v t="123.20160109140208.1"><vh>@edit 40323153_cp_w12.md</vh></v>
<v t="123.20160109140217.1"><vh>@edit 40323153_cp_w13.md</vh></v>
<v t="123.20160109140219.1"><vh>@edit 40323153_cp_w14.md</vh></v>
<v t="123.20160109140221.1"><vh>@edit 40323153_cp_w15.md</vh></v>
<v t="123.20160109140222.1"><vh>@edit 40323153_cp_w16.md</vh></v>
<v t="123.20160109140225.1"><vh>@edit 40323153_cp_w17.md</vh></v>
</v>
<v t="amd.20150919120205.1"><vh>以下為 reveal 投影片</vh></v>
<v t="amd.20150913233943.1"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6" a="E"><vh>div</vh>
<v t="amd.20150913233943.7" a="E"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1" a="E"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.1"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915155634.3" a="E"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8"><vh>body</vh>
<v t="amd.20150915155634.9" a="E"><vh>div - reveal</vh>
<v t="amd.20150915155634.10" a="E"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2" a="E"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21" a="E"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45" a="E"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62" a="E"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65" a="E"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67" a="E"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78" a="E"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81" a="E"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86" a="E"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97" a="E"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124" a="E"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133" a="E"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3" a="E"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4" a="E"><vh>body 標註</vh>
<v t="amd.20150915211351.5" a="E"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6" a="E"><vh>div class="slides"</vh>
<v t="amd.20150915211351.7"><vh>有關我的作業</vh></v>
<v t="amd.20150915211351.9"><vh>作業任務一</vh></v>
<v t="amd.20150915211351.12"><vh>第3張投影片</vh></v>
<v t="123.20151118142442.1"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118143036.1"><vh>@clean simplest2.html</vh>
<v t="123.20151118143036.2"><vh>檔案說明</vh></v>
<v t="123.20151118143036.3" a="E"><vh>html 標註</vh>
<v t="123.20151118143036.4" a="E"><vh>body 標註</vh>
<v t="123.20151118143036.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118143036.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118143036.7"><vh>有關我的作業</vh></v>
<v t="123.20151118143036.8"><vh>作業任務一</vh></v>
<v t="123.20151118143036.9"><vh>第3張投影片</vh></v>
<v t="123.20151118143036.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118143036.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224348.1"><vh>@clean simplest3.html</vh>
<v t="123.20151118224348.2"><vh>檔案說明</vh></v>
<v t="123.20151118224348.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224348.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224348.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224348.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224348.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224348.8"><vh>作業任務一</vh></v>
<v t="123.20151118224348.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224348.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224348.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224355.1"><vh>@clean simplest4.html</vh>
<v t="123.20151118224355.2"><vh>檔案說明</vh></v>
<v t="123.20151118224355.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224355.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224355.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224355.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224355.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224355.8"><vh>作業任務一</vh></v>
<v t="123.20151118224355.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224355.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224355.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224350.1"><vh>@clean simplest5.html</vh>
<v t="123.20151118224350.2"><vh>檔案說明</vh></v>
<v t="123.20151118224350.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224350.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224350.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224350.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224350.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224350.8"><vh>作業任務一</vh></v>
<v t="123.20151118224350.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224350.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224350.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224401.1"><vh>@clean simplest6.html</vh>
<v t="123.20151118224401.2"><vh>檔案說明</vh></v>
<v t="123.20151118224401.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224401.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224401.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224401.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224401.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224401.8"><vh>作業任務一</vh></v>
<v t="123.20151118224401.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224401.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224401.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224352.1"><vh>@clean simplest7.html</vh>
<v t="123.20151118224352.2"><vh>檔案說明</vh></v>
<v t="123.20151118224352.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224352.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224352.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224352.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224352.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224352.8"><vh>作業任務一</vh></v>
<v t="123.20151118224352.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224352.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224352.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20151118224358.1"><vh>@clean simplest8.html</vh>
<v t="123.20151118224358.2"><vh>檔案說明</vh></v>
<v t="123.20151118224358.3" a="E"><vh>html 標註</vh>
<v t="123.20151118224358.4" a="E"><vh>body 標註</vh>
<v t="123.20151118224358.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20151118224358.6" a="E"><vh>div class="slides"</vh>
<v t="123.20151118224358.7"><vh>有關我的作業</vh></v>
<v t="123.20151118224358.8"><vh>作業任務一</vh></v>
<v t="123.20151118224358.9"><vh>第3張投影片</vh></v>
<v t="123.20151118224358.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20151118224358.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141346.1"><vh>@clean simplest11.html</vh>
<v t="123.20160109141346.2"><vh>檔案說明</vh></v>
<v t="123.20160109141346.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141346.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141346.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141346.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141346.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141346.8"><vh>作業任務一</vh></v>
<v t="123.20160109141346.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141346.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141346.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141352.1"><vh>@clean simplest12.html</vh>
<v t="123.20160109141352.2"><vh>檔案說明</vh></v>
<v t="123.20160109141352.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141352.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141352.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141352.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141352.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141352.8"><vh>作業任務一</vh></v>
<v t="123.20160109141352.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141352.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141352.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141353.1"><vh>@clean simplest13.html</vh>
<v t="123.20160109141353.2"><vh>檔案說明</vh></v>
<v t="123.20160109141353.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141353.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141353.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141353.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141353.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141353.8"><vh>作業任務一</vh></v>
<v t="123.20160109141353.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141353.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141353.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141355.1"><vh>@clean simplest14.html</vh>
<v t="123.20160109141355.2"><vh>檔案說明</vh></v>
<v t="123.20160109141355.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141355.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141355.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141355.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141355.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141355.8"><vh>作業任務一</vh></v>
<v t="123.20160109141355.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141355.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141355.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141357.1"><vh>@clean simplest15.html</vh>
<v t="123.20160109141357.2"><vh>檔案說明</vh></v>
<v t="123.20160109141357.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141357.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141357.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141357.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141357.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141357.8"><vh>作業任務一</vh></v>
<v t="123.20160109141357.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141357.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141357.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141359.1"><vh>@clean simplest16.html</vh>
<v t="123.20160109141359.2"><vh>檔案說明</vh></v>
<v t="123.20160109141359.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141359.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141359.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141359.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141359.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141359.8"><vh>作業任務一</vh></v>
<v t="123.20160109141359.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141359.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141359.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="123.20160109141401.1"><vh>@clean simplest17.html</vh>
<v t="123.20160109141401.2"><vh>檔案說明</vh></v>
<v t="123.20160109141401.3" a="E"><vh>html 標註</vh>
<v t="123.20160109141401.4" a="E"><vh>body 標註</vh>
<v t="123.20160109141401.5" a="E"><vh>div class="reveal"</vh>
<v t="123.20160109141401.6" a="E"><vh>div class="slides"</vh>
<v t="123.20160109141401.7"><vh>有關我的作業</vh></v>
<v t="123.20160109141401.8"><vh>作業任務一</vh></v>
<v t="123.20160109141401.9"><vh>第3張投影片</vh></v>
<v t="123.20160109141401.10"><vh>第4張投影片</vh></v>
</v>
</v>
<v t="123.20160109141401.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915170743.3" a="E"><vh>head</vh>
<v t="amd.20150915170743.4"><vh>title - 標題</vh></v>
<v t="amd.20150915170743.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915170743.6"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915170743.7"><vh>body</vh>
<v t="amd.20150915170743.8" a="E"><vh>div - reveal</vh>
<v t="amd.20150915170743.9" a="E"><vh>div - slides</vh>
<v t="amd.20150915170743.10"><vh>h1 - 一般單頁</vh></v>
<v t="amd.20150915170743.11"><vh>h2</vh></v>
<v t="amd.20150915170743.12" a="E"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>h2</vh></v>
<v t="amd.20150915170743.14"><vh>h2</vh></v>
<v t="amd.20150915170743.15"><vh>h2</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>h2</vh></v>
<v t="amd.20150915170743.17"><vh>h2</vh></v>
<v t="amd.20150915170743.18"><vh>h2</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20" a="E"><vh>h2</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>h2</vh></v>
<v t="amd.20150915170743.24"><vh>p</vh></v>
<v t="amd.20150915170743.25"><vh>p</vh></v>
<v t="amd.20150915170743.26"><vh>p</vh></v>
<v t="amd.20150915170743.27"><vh>p</vh></v>
<v t="amd.20150915170743.28"><vh>p</vh></v>
<v t="amd.20150915170743.29"><vh>p</vh></v>
<v t="amd.20150915170743.30"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915170743.31"><vh>h2</vh></v>
<v t="amd.20150915170743.32"><vh>p</vh>
<v t="amd.20150915170743.33"><vh>a</vh></v>
<v t="amd.20150915170743.34"><vh>a</vh></v>
<v t="amd.20150915170743.35"><vh>a</vh></v>
<v t="amd.20150915170743.36"><vh>a</vh></v>
<v t="amd.20150915170743.37"><vh>a</vh></v>
<v t="amd.20150915170743.38"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.39"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915170743.40" a="E"><vh>p</vh>
<v t="amd.20150915170743.41"><vh>a</vh></v>
<v t="amd.20150915170743.42"><vh>a</vh></v>
<v t="amd.20150915170743.43"><vh>a</vh></v>
<v t="amd.20150915170743.44"><vh>a</vh></v>
<v t="amd.20150915170743.45"><vh>a</vh></v>
<v t="amd.20150915170743.46"><vh>a</vh></v>
<v t="amd.20150915170743.47"><vh>a</vh></v>
<v t="amd.20150915170743.48"><vh>a</vh></v>
<v t="amd.20150915170743.49"><vh>a</vh></v>
<v t="amd.20150915170743.50"><vh>a</vh></v>
<v t="amd.20150915170743.51"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.52"><vh>h2</vh></v>
<v t="amd.20150915170743.53"><vh>p</vh>
<v t="amd.20150915170743.54"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.55"><vh>a</vh></v>
<v t="amd.20150915170743.56"><vh>h2</vh></v>
<v t="amd.20150915170743.57" a="E"><vh>pre</vh>
<v t="amd.20150915170743.58"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.59"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915170743.60" a="E"><vh>pre</vh>
<v t="amd.20150915170743.61"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.62" a="E"><vh>div</vh>
<v t="amd.20150915170743.63"><vh>h2</vh></v>
<v t="amd.20150915170743.64"><vh>pre</vh>
<v t="amd.20150915170743.65"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915170743.66"><vh>h2</vh></v>
<v t="amd.20150915170743.67"><vh>h2</vh></v>
<v t="amd.20150915170743.68"><vh>p</vh></v>
<v t="amd.20150915170743.69"><vh>pre</vh>
<v t="amd.20150915170743.70"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.71"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915170743.72"><vh>p</vh></v>
<v t="amd.20150915170743.73" a="E"><vh>pre</vh>
<v t="amd.20150915170743.74"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.75" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915170743.76" a="E"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.79"><vh>h2</vh></v>
<v t="amd.20150915170743.80" a="E"><vh>ul</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.85"><vh>h2</vh></v>
<v t="amd.20150915170743.86"><vh>ol</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.90"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915170743.91" a="E"><vh>table</vh>
<v t="amd.20150915170743.92"><vh>thead</vh>
<v t="amd.20150915170743.93"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.110"><vh>h2</vh></v>
<v t="amd.20150915170743.111"><vh>p</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
</v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
<v t="amd.20150915170743.114"><vh>h2</vh></v>
<v t="amd.20150915170743.115"><vh>p</vh>
<v t="amd.20150915170743.116"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.117"><vh>h2</vh></v>
<v t="amd.20150915170743.118" a="E"><vh>p</vh>
<v t="amd.20150915170743.119"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.120"><vh>p</vh>
<v t="amd.20150915170743.121"><vh>em</vh></v>
</v>
<v t="amd.20150915170743.122"><vh>h2</vh></v>
<v t="amd.20150915170743.123"><vh>p</vh>
<v t="amd.20150915170743.124"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.125"><vh>iframe</vh></v>
<v t="amd.20150915170743.126"><vh>h2</vh></v>
<v t="amd.20150915170743.127" a="E"><vh>p</vh>
<v t="amd.20150915170743.128"><vh>code</vh></v>
<v t="amd.20150915170743.129"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.130"><vh>h2</vh></v>
<v t="amd.20150915170743.131"><vh>p</vh>
<v t="amd.20150915170743.132"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.133"><vh>pre</vh>
<v t="amd.20150915170743.134"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.136"><vh>p</vh></v>
<v t="amd.20150915170743.137" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
<v t="amd.20150915170743.149"><vh>script</vh></v>
<v t="amd.20150915170743.150"><vh>script</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="123.20151118142442.1">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第一周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118143036.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118143036.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第二周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118143036.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118143036.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118143036.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118143036.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118143036.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118143036.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118143036.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118143036.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第二周)&lt;/p&gt;
    &lt;p&gt;1.修改投影片 2.將python.properties中的V:\IDE\Python33修改成V:\anaconda3 3.討論為何push上去github卻無法開啟網頁,怎麼處理以及更新資料&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118143036.9">&lt;section&gt;
    &lt;p&gt;第二周心得分享&lt;/p&gt;
    &lt;p&gt;發現這禮拜對於上課的內容大部份都不太清楚，連一開始的LEO對我來說就有些難度了，沒想到做到最後後，一檢查結果居然出現"404"，聽了老師的說明後才了解發生了甚麼事情，雖然很灰心不過還是得繼續完成他。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224348.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224348.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第三周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224348.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224348.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224348.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224348.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224348.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224348.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224348.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224348.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第三周)&lt;/p&gt;
    &lt;p&gt;1.繼續完成第二周作業 2學習繪圖軟體,了解並且如何操作 3.下載solvespace的檔案&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224348.9">&lt;section&gt;
    &lt;p&gt;第三周心得分享&lt;/p&gt;
    &lt;p&gt;進入了第3周，發現自己累積的作業越來越多，不了解的也越來越多，如果現在再不跟上進度，很可能之後會有來不急的情況。不過對於課程的某些東西還滿有自信的。雖然很多部分都是需要依靠同學們的協助，但是我都有漸漸地學下來。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224350.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224350.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第五周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224350.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224350.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224350.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224350.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224350.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224350.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224350.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224350.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第五周)&lt;/p&gt;
    &lt;p&gt;1.完成未完成的投影片 2.每一小組派出兩個人實物測繪 3.reveal有更新過,更新reavel,EX：如 bootstrap3改成octopress&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224350.9">&lt;section&gt;
    &lt;p&gt;第五周心得分享&lt;/p&gt;
    &lt;p&gt;老師在這周說明了更新後reaveal2的差異，原來是只有bootstrap3改成octopress，剩下的地方就大同小異，正在實物測繪的組員進展好像也不是很順利，希望下周我們的情況會改善。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224352.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224352.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第七周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224352.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224352.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224352.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224352.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224352.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224352.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224352.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224352.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第七周)&lt;/p&gt;
    &lt;p&gt;1.更改倉儲裡面的Leo 2.建立班級倉儲裡的使用者&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224352.9">&lt;section&gt;
    &lt;p&gt;第七周心得分享&lt;/p&gt;
    &lt;p&gt;今天決定要將之前未完成的功課完成，雖然累積了多功課，不過現在不加把勁，到時候一定會做不完。也很謝謝協助班上同學的人，他們都會不厭其煩的教導大家如何操作，真的超感動的。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224355.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224355.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第四周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224355.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224355.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224355.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224355.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224355.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224355.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224355.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224355.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第四周)&lt;/p&gt;
    &lt;p&gt;1.繼續完成未完成的投影片 2.使用繪圖軟體,畫出例題中的圖形 3.準備實物測繪&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224355.9">&lt;section&gt;
    &lt;p&gt;第四周心得分享&lt;/p&gt;
    &lt;p&gt;這次上課因為網路的問題導致有些操作沒辦法做，於是我就先完成上次沒有作完的功課。也開始分工合作，一些人實物測繪依一些人做投影片，我在這次的操作出了些順序問題，導致檔案在上傳的時候出了些問題。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224358.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224358.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第八周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224358.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224358.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224358.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224358.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224358.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224358.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224358.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224358.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第八周)&lt;/p&gt;
    &lt;p&gt;1.進入班級協同倉儲改自己的檔案 2.解決衝突 (1)先將Leo檔打開至SciTE (2)尋找&lt;&lt;&lt;&lt;&lt;&lt;&lt; (3)因為有新版本及舊版本,必須要將舊版本的刪掉 (4)它會有x7把它們通通刪掉 (5)他們前面還會有一些等號也要把它刪掉 (6)儲存之後再重開一次檔案就好囉&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224358.9">&lt;section&gt;
    &lt;p&gt;第八周心得分享&lt;/p&gt;
    &lt;p&gt;已經接近期中報告的期限了，雖然在學校有做了一些進度，不過孩時沒版法把全部完成，還是需要利用回家的時間來繼續完成他。對於最近的內容都有一種越來越熟練的感覺，可能是越用越熟悉的關系吧。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224401.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20151118224401.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第六周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224401.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20151118224401.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20151118224401.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20151118224401.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20151118224401.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224401.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20151118224401.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20151118224401.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第六周)&lt;/p&gt;
    &lt;p&gt;1.完成未完成的投影片 2.實物測繪---腳踏車 3.已建立班上協同倉儲,首先建立協同倉儲者 4.git clone 2015fallcadpa(可先到tmp後再clone) 5.切換分支 6.找到資料夾裡有user,複製9999,貼上並改成自己的學號並進入 7.刪除有關9999的資料(一個是網址檔,一個是在pelican裡的content,兩個檔案都刪掉) 8.在Leo複製path9999,改學號 9.有關9999全改成自己的學號(需於自己的path裡面改) 10.按path 40323153點user-pelican&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20151118224401.9">&lt;section&gt;
    &lt;p&gt;第六周心得分享&lt;/p&gt;
    &lt;p&gt;離期中考越來越近了，幫上同學也越來越多人在推檔案上去，可能是因為太多人同時在做一樣的動作，導致電腦的速度有點慢，雖然前面有出錯，不過後面經過同學的協助，也是順利完成了。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141346.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141346.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十一周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141346.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141346.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141346.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141346.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141346.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141346.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141346.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141346.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十一周)&lt;/p&gt;
    &lt;p&gt;1.多下載一份班上倉儲並回復到原始的版本(git reset --hard ssl網址)。&lt;/p&gt;&lt;p&gt; 2.舊版內自己的內容，獨立修改成自己的檔案(參考老師範例)，並存在新版的班上倉儲中(user內自己的資料夾)。&lt;/p&gt;&lt;p&gt;3.新版倉儲存檔後推回遠端即可(組別和個人檔案分開管理)。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141346.9">&lt;section&gt;
    &lt;p&gt;第十一周心得分享&lt;/p&gt;
    &lt;p&gt;此週目的為建立個人檔案，因為在user的節點已經被刪除了，因此這次大家都要回到上一個版次，去找到自己在之前的檔案根內容，在複製的過程中雖然有些麻煩，但是這樣一來就不會有發生像是其中考前的問題了。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141352.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141352.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十二周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141352.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141352.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141352.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141352.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141352.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141352.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141352.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141352.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十二周)&lt;/p&gt;
    &lt;p&gt;1.下載 fix檔案。&lt;/p&gt;&lt;p&gt;2.下載leo壓縮檔，放置於fix資料夾內。&lt;/p&gt;&lt;p&gt;3.新增fix路徑 copy leo-editor-broke-abbrev.zip "C:\Ana3_2015\data\" 路徑依自己的檔案修改。&lt;/p&gt;&lt;p&gt;4.修改start.bat內pip install leo-editor-broke-abbrev.zip。&lt;/p&gt;&lt;p&gt;5.啟動fix ，將相對應得檔案複製到指定位置即可。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141352.9">&lt;section&gt;
    &lt;p&gt;第十二周心得分享&lt;/p&gt;
    &lt;p&gt;這次修改了fix的路徑，雖然說是跟著老師跟同學一起操作，但是有許多的操作我都不太明白是甚麼意思，有些的程序還請同學協助我的，真的很感謝那些在班上教大家的人。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141353.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141353.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十三周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141353.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141353.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141353.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141353.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141353.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141353.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141353.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141353.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十三周)&lt;/p&gt;
    &lt;p&gt;1.利用onshape繪製零件。&lt;/p&gt;&lt;p&gt;2.使用螢幕錄影(camstudio)，錄影所有繪製零件。&lt;/p&gt;&lt;p&gt;3.將上傳影片至vimeo，以取得連結。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141353.9">&lt;section&gt;
    &lt;p&gt;第十三周心得分享&lt;/p&gt;
    &lt;p&gt;這一週將利用onshape來繪製零件，因為電腦有些問題，再加上時不時網路的斷線，導至今天的會圖不怎麼順利，一直發生錯誤，或是需要請教別人的地方，雖然是這樣不過希望不會影響到後面幾週的進度。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141355.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141355.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十四周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141355.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141355.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141355.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141355.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141355.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141355.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141355.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141355.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十四周)&lt;/p&gt;
    &lt;p&gt;1.利用onshape繪製零件。&lt;/p&gt;&lt;p&gt;2.使用螢幕錄影(camstudio)，錄影所有繪製零件。&lt;/p&gt;&lt;p&gt;3.將上傳影片至vimeo，以取得連結。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141355.9">&lt;section&gt;
    &lt;p&gt;第十四周心得分享&lt;/p&gt;
    &lt;p&gt;這一週也是持續利用onshape來繪製零件，在操作上已經沒有像上次如此的生疏，不過在其他操作上還是有不太能理解的地方，歲然說之前已經有學過一些繪圖軟體，不過在次在英文版的情況下，很多的生字，使我變得非常遲鈍，英文還須好好加油。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141357.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141357.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十五周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141357.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141357.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141357.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141357.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141357.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141357.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141357.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141357.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十五周)&lt;/p&gt;
    &lt;p&gt;1.利用creo繪製零件。&lt;/p&gt;&lt;p&gt;2.利用onshape繪製零件，並且組立。&lt;/p&gt;&lt;p&gt;3.使用螢幕錄影(camstudio)，錄影所有繪製零件、組立之過程。&lt;/p&gt;&lt;p&gt;4.將上傳影片至vimeo，以取得連結。&lt;/p&gt;&lt;p&gt;5.將creo繪製的零件檔轉成stl檔案。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141357.9">&lt;section&gt;
    &lt;p&gt;第十五周心得分享&lt;/p&gt;
    &lt;p&gt;此週利用onshape組立零件，雖然在操作上我還非常的生疏，但是因為之前有學過其他軟體的組立，因此在操作上韓還是可以利用同樣的邏輯思考去組立，並且發現了onshape可以將零件轉成許多不同的檔案。。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141359.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141359.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十六周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141359.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141359.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141359.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141359.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141359.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141359.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141359.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141359.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十六周)&lt;/p&gt;
    &lt;p&gt;1.利用onshape繪製零件。&lt;/p&gt;&lt;p&gt;2.使用螢幕錄影(camstudio)，錄影所有繪製零件、組立之過程。&lt;/p&gt;&lt;p&gt;3.將上傳影片至vimeo，以取得連結。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141359.9">&lt;section&gt;
    &lt;p&gt;第十六周心得分享&lt;/p&gt;
    &lt;p&gt;在onshape上，已經可以利用各方法來會圖了，藉由板次的設定，讓大家都可以看到各個使用者繪圖跟設計，或是哪個使用者發生設計錯誤。至近對於onshape已經有用過數次了，對於操作也越來越熟練，希望未來onshape的功能可以越來越完善。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141401.1">@language xml
@tabwidth -4
@others

</t>
<t tx="123.20160109141401.10">&lt;section&gt;
    &lt;p&gt;自評分數&lt;/p&gt;
    &lt;p&gt;1.第十七周:75&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141401.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="123.20160109141401.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="123.20160109141401.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="123.20160109141401.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="123.20160109141401.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141401.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="123.20160109141401.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
   &lt;p&gt;&lt;font size="5" face="Arial"&gt;&lt;marquee border="0"&gt;版本於 2016 / 01 / 09 更新&lt;/marquee&gt;&lt;/font&gt;&lt;/p&gt;
    &lt;br&gt;
    &lt;br&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="123.20160109141401.8">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第十七周)&lt;/p&gt;
    &lt;p&gt;1.利用onshape繪製零件。&lt;/p&gt;&lt;p&gt;2.使用螢幕錄影(camstudio)，錄影所有繪製零件、組立之過程。&lt;/p&gt;&lt;p&gt;3.將上傳影片至vimeo，以取得連結。
&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="123.20160109141401.9">&lt;section&gt;
    &lt;p&gt;第十七周心得分享&lt;/p&gt;
    &lt;p&gt;這周已經是期末考的前一周了，但是目前看來我還是有許多的功課未完成，可能沒辦法在今天就完成，都需要利用回家的時間了，不過還好這次因為是只用不同的方式，不會像上次一樣推到一半如果有其他人推錯了，就會使得整個檔案出問題，希望回家的操作可以一切順利。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915153206.1">2015.09.15

將 2014 的 index.html 與 cadpbw1.html 與 2015 最新的 reveal 框架檔案合併
此後將以 v31ref.html 中的語法為主

</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
        &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.110">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.112">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.114">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.115">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.116">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915170743.117">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.118">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.119">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.120">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.121">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915170743.122">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.123">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.124">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915170743.125">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.126">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.127">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.128">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915170743.129">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.130">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.131">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.132">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915170743.133">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.134">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.136">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915170743.149">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.150">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.17">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.18">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.31">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.32">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.33">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.34">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.35">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.36">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.37">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.38">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.39">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;reveal.js - The HTML Presentation Framework&lt;/title&gt;

</t>
<t tx="amd.20150915170743.40">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915170743.41">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915170743.42">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.43">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.44">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.45">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.46">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915170743.47">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.5">&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="Hakim El Hattab"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915170743.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915170743.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915170743.52">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.53">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.54">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915170743.55">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915170743.56">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.57">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.58">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915170743.6">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915170743.60">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915170743.61">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915170743.62">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.63">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915170743.64">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915170743.65">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.66">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.67">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.68">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.69">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.70">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915170743.71">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.72">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915170743.73">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.74">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.79">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.8">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.80">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.85">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915170743.90">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915170743.91">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;p&gt;第一周心得分享&lt;/p&gt;
    &lt;p&gt;已經的很長時間沒有用過python了，覺得有點生疏，這次用github網站建立分支後，了解如何改變分支，雖然有些困難不過還是得繼續加油。希望在下周可以更了解上課內容。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;班級協同投影片&lt;/h1&gt;
    &lt;p&gt;四設計二甲&lt;/p&gt;
    &lt;p&gt;MY PROFILE&lt;/p&gt;
&lt;p&gt;40323153 劉彥沛&lt;/p&gt;
&lt;/section&gt;
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;p&gt;筆記(第一周)&lt;/p&gt;
    &lt;p&gt;1.新建github倉儲,新增的同時Remade需打勾 2.git clone 自己倉儲的網址,之後進入資料夾cadpa_test 3.git branch 4.git branch gh-pages 5.git branch 6.git checkout gh-pages 將reaval的檔案download,除了 Remade他複製 到自己的資料夾 輸入指令 1.git add -A 2.git commit -m "1001" 3.git push origin gh-pages 4.輸入自己的帳號及密碼 5.檢查是否成功,輸入網址即可&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102209.1">本專案

利用 Jupyter 產生 IPython notebook, 然後整合入 pelican 網誌

利用 github pages 在 github.io 網站上伺服網頁資料

利用 reveal.js 產生投影片

利用 pelican 與 Markdown 產生網誌文章

利用 disqus 建立互動留言系統</t>
<t tx="amd.20150919102541.1">在 Anaconda 3 中只要

    pip install pelican Markdown 

安裝 pelican 與 Markdown Python 模組即可

若是在 Ubuntu 中則可以透過

    sudo pip3 install pelican Markdown 

安裝 pelican 與 Markdown Python 模組</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103341.1">REM start.bat 中 取電腦 IP 與 Jupyter 啟動

REM 取 IPV4 IP address
for /f "delims=[] tokens=2" %%a in ('ping -4 %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 取 IPV6 IP address
REM for /f "delims=[] tokens=2" %%a in ('ping %computername% -n 1 ^| findstr "["') do (set thisip=%%a)
REM echo %thisip%
REM 啟動 Jupyter
cd notebook
start %Disk%:\Anaconda3\python.exe "%Disk%:\Anaconda3\Scripts\ipython-script.py" notebook --ip=%thisip% --certfile=%Disk%:\home\ssl_cert.pem --profile=nbserver</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919103428.1"></t>
<t tx="amd.20150919103923.1">home/.ipython/profile_nbserver/ipython_notebook_config.py

內容為:

# Password to use for web authentication
c = get_config()
# password is  "2015cp"
c.NotebookApp.password = u'sha1:864c0bcdb94e:8a396ef692ef3cc552177f1b1c48cec70c7a32df'
c.NotebookApp.port = 8888

產生 password 的程式碼:

from IPython.lib import passwd
passwd()

</t>
<t tx="amd.20150919104249.1">@language python
# show 出 ipython notebook 所使用的 profile 目錄
# 這裡應該會傳回 {'location': 'y:\\home\\.ipython\\profile_nbserver'}
# 表示 custom.js 位於 'y:\\home\\.ipython\\profile_nbserver\\static\\custom'
'''在 custom.js 中加入
require(["base/js/events"], function (events) {
    events.on("app_initialized.NotebookApp", function () {
    /* load your extension here */
    IPython.load_extensions('read-only');
    });
});
就可以自動導入'y:\\home\\.ipython\\nbextensions\read-only.js' 延伸檔案
read-only toggle 為 Alt+R
'''
# 以下為操作方法
'''當使用者選擇某一 cell, 然後按下 Alt+R, 則 cell 內原本為灰色將會變成白色, 表示
cell 為 read only
''''''
import IPython
ip=IPython.get_ipython()
ip.config.ProfileDir </t>
<t tx="amd.20150919112415.1">使用 Vimeo</t>
<t tx="amd.20150919112710.1"></t>
<t tx="amd.20150919113340.1"></t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
os.system('''pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-bootstrap3
''')
g.es("pelican 執行完畢")</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
</tnodes>
</leo_file>
